# Docker Compose file for FormatMagic development environment

services:
  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: formatmagic-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost/api
    restart: unless-stopped
    networks:
      - formatmagic-network
    depends_on:
      - backend

  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: formatmagic-backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=http://localhost
    volumes:
      # 本地存储挂载
      - ./data/uploads:/app/uploads
      - ./data/outputs:/app/outputs
      - ./data/temp:/app/temp
    restart: unless-stopped
    networks:
      - formatmagic-network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: formatmagic-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # SSL证书挂载 (如果需要)
      # - ./ssl:/etc/ssl/certs
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    networks:
      - formatmagic-network

networks:
  formatmagic-network:
    driver: bridge

# 数据卷 (用于持久化存储)
volumes:
  uploads:
  outputs:
  temp:
