version: '3.8'

services:
  # 前端服务 - 生产环境
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: formatmagic-frontend-prod
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://your-domain.com/api
    restart: always
    networks:
      - formatmagic-network
    depends_on:
      - backend
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # 后端服务 - 生产环境
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: formatmagic-backend-prod
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=https://your-domain.com
    volumes:
      # 生产环境数据目录
      - /opt/formatmagic/uploads:/app/uploads
      - /opt/formatmagic/outputs:/app/outputs
      - /opt/formatmagic/temp:/app/temp
      # 日志目录
      - /opt/formatmagic/logs:/app/logs
    restart: always
    networks:
      - formatmagic-network
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Nginx反向代理 - 生产环境
  nginx:
    image: nginx:alpine
    container_name: formatmagic-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # SSL证书 (请替换为您的实际证书路径)
      # - /etc/letsencrypt/live/your-domain.com:/etc/ssl/certs:ro
      # 日志
      - /var/log/nginx:/var/log/nginx
    restart: always
    depends_on:
      - frontend
      - backend
    networks:
      - formatmagic-network

networks:
  formatmagic-network:
    driver: bridge

# 生产环境数据卷
volumes:
  uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/formatmagic/uploads
  outputs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/formatmagic/outputs
